help:
  just --list --unsorted

build:
  cargo build --release
alias b := build

dev:
  cargo watch -cx lbuild
alias d := dev

run CMD:
  cargo run -- {{CMD}}
alias r := run

cron:
  crontab res/jobs.crontab

install: build cron
  @mkdir -p bin
  cp target/release/xsys bin/xsys
alias i := install
