help:
  just --list --unsorted

build:
  cargo build --release
alias b := build

install:
  mkdir bin
  cp target/release/xsys bin/
alias i := install

dev:
  cargo watch -cx lbuild
alias d := dev

run CMD:
  cargo run -- {{CMD}}
alias r := run
