[alias]
t = "nextest run"
rr = "run --release"

[net]
retry = 3
git-fetch-with-cli = true
offline = false

[cargo-new]
vcs = "none" # "none" | "git" ...

[target.x86_64-unknown-linux-gnu]
rustflags = [ "-Clink-arg=-fuse-ld=lld" ]

[target.aarch64-unknown-linux-gnu]
rustflags = [ "-Clink-arg=-fuse-ld=lld" ]
