[manager]
ratio = [1, 2, 5]
show_hidden = true
show_symlink = true
tab_size = 2

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"
