import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[shell]
program = "zsh"

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 7
offset.x = 0
offset.y = -2
bold.family = "JetBrainsMono NF"
bold.style = "Bold"
bold_italic.family = "JetBrainsMono NF"
bold_italic.style = "Bold Italic"
italic.family = "JetBrainsMono NF"
italic.style = "Italic"
normal.family = "JetBrainsMono NF"
normal.style = "Regular"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"
padding.x = 0
padding.y = 4

[debug]
render_timer = false
print_events = false
highlight_damage = false
prefer_egl = false
