import = ["/Users/nico/.config/alacritty/theme-dark.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 7

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = -2

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
