#!/usr/bin/env bash

gc_enabled=0
check=0
update=0

usage() {
    echo "Usage: $0 [-g|--gc] [-c|--check] [-u|--update]"
    echo "  -g, --gc         Enable garbage collection"
    echo "  -c, --check      Test rebuild without applying changes"
    echo "  -u, --update     Update flake before rebuild"
    exit 1
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -g|--gc) gc_enabled=0 ;;
        -c|--check) check=1 ;;
        -u|--update) update=1 ;;
        *) usage ;;
    esac
    shift
done

if [[ $gc_enabled -eq 1 ]]; then
    echo "Running garbage collection..."
    nix-collect-garbage -d
fi

if [[ $check -eq 1 ]]; then
    echo "Checking flake..."
    nix flake check ~/.nixfiles
fi

if [[ $update -eq 1 ]]; then
    echo "Updating flake..."
    nix flake update ~/.nixfiles
fi

nixos_rebuild_command=" $( [[ $check -eq 1 ]] && echo "test" || echo "switch" )"
cmd="sudo nixos-rebuild $nixos_rebuild_command --flake ~/.nixfiles#$(hostname) -v"

echo "Executing: $cmd"
eval $cmd
