#!/usr/bin/env bash

gc_enabled=0
dry_run=0
update=0

usage() {
    echo "Usage: $0 [-g|--no-gc] [-t|--test] [-u|--update]"
    echo "  -g, --no-gc      Disable garbage collection"
    echo "  -d, --dry-run    Test rebuild without applying changes"
    echo "  -u, --update     Update flake before rebuild"
    exit 1
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -g|--no-gc) gc_enabled=0 ;;
        -d|--dry-run) dry_run=1 ;;
        -u|--update) update=1 ;;
        *) usage ;;
    esac
    shift
done

if [[ $gc_enabled -eq 1 ]]; then
    echo "Running garbage collection..."
    nix-collect-garbage -d
fi

if [[ $update -eq 1 ]]; then
    echo "Updating flake..."
    nix flake update ~/.nixfiles
fi

nixos_rebuild_command=" $( [[ $dry_run -eq 1 ]] && echo "test" || echo "switch" )"
cmd="sudo nixos-rebuild $nixos_rebuild_command --flake ~/.nixfiles#$(hostname) -v"

echo "Executing: $cmd"
eval $cmd
