#!/usr/bin/env bash

setup_session() {
  local SESH=$1
  local KEYS=$2

  tmux has-session -t $SESH 2>/dev/null

  if [ $? != 0 ]; then
     tmux new-session -s $SESH -d
     tmux send-keys -t $SESH "$KEYS" C-m
  fi

  tmux send-keys -t $SESH C-l
  tmux attach-session -t $SESH
}

SESSION_NAME=$1

case $SESSION_NAME in
  "py_repl")
    setup_session "py_repl" "nix-shell ~/.nixfiles/shells/pymath.nix --run 'ipython --no-banner'"
    ;;
  "notes")
    setup_session "notes" "nvim ~/cloud/gdrive/notes/"
    ;;
  "dev")
    setup_session "dev" "."
    ;;
  *)
    echo "Unknown session name: $SESSION_NAME"
    exit 1
    ;;
esac

