#!/usr/bin/env bash

SESSION_NAME=$1
SHOULD_CLEAR=$2

setup_session() {
  local SESH=$1
  local KEYS=$2

  if ! tmux has-session -t "$SESH" 2>/dev/null; then
     tmux new-session -s "$SESH" -d

    if [ "$SHOULD_CLEAR" = "clear" ]; then
      tmux send-keys -t "$SESH" "$KEYS" C-m
    fi
  fi

  tmux send-keys -t "$SESH" C-l
  tmux attach-session -t "$SESH"
}

case $SESSION_NAME in
  "py_repl")
    setup_session "py_repl" "nix-shell ~/.nixfiles/shells/pymath.nix --run 'ipython --no-banner'"
    ;;
  "notes")
    setup_session "notes" "nvim ~/cloud/gdrive/notes/"
    ;;
  "dev")
    setup_session "dev" "."
    ;;
  *)
    echo "Unknown session name: $SESSION_NAME"
    exit 1
    ;;
esac

