#!/usr/bin/env bash

set -euo pipefail

I3_CONFIG="$HOME/.config/i3/config"
DUNST_CONFIG="$HOME/.config/dunst/dunstrc"
ALACRITTY_CONFIG="$HOME/.config/alacritty"
GTK_CONFIG="$HOME/.config/gtk-3.0"
NVIM_CONFIG="$HOME/.config/nvim/lua/config"
ROFI_CONFIG="$HOME/.config/rofi"
BRAVE_CONFIG="$HOME/.config/chrome-theme"

LIGHT_THEME="light"
DARK_THEME="dark"

declare -A mode_bg=( ["light"]="#FBF1C7" ["dark"]="#282828" )
declare -A mode_text=( ["light"]="#076678" ["dark"]="#83A598" )
declare -A mode_border=( ["light"]="#458588" ["dark"]="#458588" )

declare -A mode_background=( ["light"]="#FBF1C7cc" ["dark"]="#282828cc" )
declare -A mode_wallpaper=( ["light"]="gruvbox-light-blue.png" ["dark"]="gruvbox-dark-blue.png" )
declare -A mode_nvim=( ["light"]="kanagawa-lotus" ["dark"]="kanagawa" )

set_theme() {
  local mode=$1

  ln -sf "$ALACRITTY_CONFIG/$mode.toml" "$ALACRITTY_CONFIG/theme.toml"
  ln -sf "$GTK_CONFIG/$mode.ini" "$GTK_CONFIG/settings.ini"
  ln -sf "$NVIM_CONFIG/colors/$mode.lua" "$NVIM_CONFIG/colors/init.lua"
  ln -sf "$NVIM_CONFIG/theme/$mode.lua" "$NVIM_CONFIG/theme/init.lua"
  ln -sf "$ROFI_CONFIG/$mode.rasi" "$ROFI_CONFIG/theme.rasi"
  ln -sf "$BRAVE_CONFIG/$mode.json" "$BRAVE_CONFIG/manifest.json"
  rm -f $BRAVE_CONFIG/Cached\ Theme.pak

  sed -i "s/set \$bg .*/set \$bg ${mode_bg[$mode]}/" "$I3_CONFIG"
  sed -i "s/set \$text .*/set \$text ${mode_text[$mode]}/" "$I3_CONFIG"
  sed -i "s/set \$border .*/set \$border ${mode_border[$mode]}/" "$I3_CONFIG"
  sed -i "s/background = .*/background = \"${mode_background[$mode]}\"/" "$DUNST_CONFIG"

  touch "$ALACRITTY_CONFIG/alacritty.toml"
  pkill dunst && dunst > /tmp/dunst.log 2>&1 &
  nitrogen --save --set-zoom-fill "$HOME/.nixfiles/assets/${mode_wallpaper[$mode]}"
  i3-msg reload

  for SERVER in $(nvr --serverlist); do
    nvr --nostart --servername $SERVER \
      -cc "lua vim.api.nvim_set_option('background', '$mode')" \
      -cc "colorscheme ${mode_nvim[$mode]}"
  done
}

if ~/.scripts/is-light-mode; then
  set_theme "$DARK_THEME"
else
  set_theme "$LIGHT_THEME"
fi
