#!/usr/bin/env bash

if [ $# -eq 1 ]; then
  echo "use_nix $1" > .envrc
  echo "using nix shell @ $1"
else
  echo "use_nix" > .envrc
  echo "with import <nixpkgs> {}; mkShell {
    packages = [
      pkg-config
    ];
  }
  " > shell.nix
  echo "using local nix shell"
fi

direnv allow

