#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    echo "" > .envrc
    for file in "$@"; do
        echo "use_nix $file;" >> .envrc
        echo "using nix shell @ $file"
    done
else
    echo "use_nix" > .envrc
    echo "with import <nixpkgs> {}; mkShell {
        packages = [
            pkg-config
        ];
    }" > shell.nix
    echo "using local nix shell"
fi

direnv allow

