[[language]]
name = "rust"
formatter = { command = "cargo fmt" }

[language.debugger]
command = "~/.codelldb/extension/adapter/codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
