[[language]]
name = "rust"
formatter = { command = "cargo fmt" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
